#
# haproxy service
#
# In inventory - 
# masters=[{'name': 'name1', 'address': '1.2.3.4'}]
# infra_nodes=[{'name': 'name1', 'address': '1.2.3.5'}]
#
- hosts: haproxy

  vars:

  tasks:
    - name: haproxy package
      action: package name=haproxy state=installed

    - name: openshift proxy configuration
      action: template src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
      notify:
      - restart haproxy

    - name: haproxy service
      action: systemd name=haproxy enabled=yes state=started

    - name: firewalld package
      action: package name=firewalld state=installed

    - name: firewalld service
      action: systemd name=firewalld enabled=yes state=started

    - name: http port
      firewalld:
        zone: public
        service: http
        state: enabled
        permanent: yes
        immediate: yes

    - name: https port
      firewalld:
        zone: public
        service: https
        state: enabled
        permanent: yes
        immediate: yes

    - name: http-alt port
      firewalld:
        zone: public
        port: 8443/tcp
        state: enabled
        permanent: yes
        immediate: yes

  handlers:
    - name: restart haproxy
      systemd: name=haproxy state=restarted
