#
# haproxy service
#
- hosts: all
  become: true

  vars:

  tasks:
    - name: haproxy package
      action: package name=haproxy state=installed

    - name: haproxy service
      action: systemd name=haproxy enabled=yes state=started

    - name: firewalld package
      action: package name=firewalld state=installed

    - name: firewalld service
      action: systemd name=firewalld enabled=yes state=started

    - name: http port
      firewalld:
        zone: public
        service: http
        state: enabled
        permanent: yes
        immediate: yes

    - name: https port
      firewalld:
        zone: public
        service: https
        state: enabled
        permanent: yes
        immediate: yes

    - name: http-alt port
      firewalld:
        zone: public
        port: 8443/tcp
        state: enabled
        permanent: yes
        immediate: yes

- hosts: localhost
  become: false
  tags:
  - configure

  tasks:
    - name: Find Floating IP Addresses
      os_floating_ip_facts:

    - name: Find Masters and Infrastructure Nodes
      os_server_facts:
        pattern: "(master|infra-node)-[0-9].control.{{ domain_name }}"


- hosts: all
  become: true
  tags: configure
  tasks:
    - name: openshift proxy configuration
      action: template src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
      notify:
      - restart haproxy

  handlers:
    - name: restart haproxy
      systemd: name=haproxy state=restarted

