#
# haproxy service
#
# In inventory - 
# masters=[{'name': 'name1', 'address': '1.2.3.4'}]
# infra_nodes=[{'name': 'name1', 'address': '1.2.3.5'}]
#
- hosts: haproxy

  vars:

  tasks:
    - name: haproxy package
      action: package name=haproxy state=installed

    - name: openshift proxy configuration
      action: template src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
      notify:
      - restart haproxy

    - name: haproxy service
      action: systemd name=haproxy enabled=yes state=started

    - name: firewalld package
      action: package name=firewalld state=installed

    - name: firewalld service
      action: systemd name=firewalld enabled=yes state=started

    - name: http port
      action: firewalld service=http permanent=true state=enabled
    - name: https port
      action: firewalld service=https permanent=true state=enabled
    - name: alternate https port
      action: firewalld port=8443/tcp permanent=true state=enabled

  handlers:
    - name: restart haproxy
      systemd: name=haproxy state=restarted
